=== pablodmv/frameworkdc/FrameworkDC/src/xmlParse/mvc.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Elemento raÃ­z -->
<!ELEMENT mvc-config (command-mappings)>

<!-- Conjungo de mapeos de comandos -->
<!ELEMENT command-mappings (command)*>

<!-- Comando -->
<!ELEMENT command (forward)*>
<!ATTLIST command
    type CDATA #IMPLIED
    forwardTo CDATA #IMPLIED
    path CDATA #IMPLIED
>

<!ELEMENT forward EMPTY>
<!ATTLIST forward
    path CDATA #IMPLIED
    name CDATA #IMPLIED
>

=== pablodmv/frameworkdc/trunk/Libreta/Libreta-war/web/WEB-INF/mvc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mvc-config SYSTEM "mvc.dtd">
<!--
    Document   : mvcTest.xml
    Created on : 23 de octubre de 2010, 04:47 PM
    Author     : Gustavo Leites
    Description:
        Purpose of the document follows.
-->

<mvc-config>
    <command-mappings>
        <command path="/Bienvenido" forwardTo="/Bienvenido.jsp"/>
        <command path="/Login" forwardTo="/Login.jsp"/>
        <command path="/addUser" forwardTo="/altaUsuario.jsp"/>
        <command path="/editUser" forwardTo="/EditarUsuario.jsp"/>
        <command path="/deleteUser" forwardTo="/EliminarUsuario.jsp"/>
        <command path="/queryUser" forwardTo="/QueryUsuario.jsp"/>

        <command path="/Check" type="concreteCommands.ComandoConcreto">
            <forward name="Success" path="/Bienvenido.jsp"/>
            <forward name="Fail" path="/Error.jsp"/>
        </command>

        <command path="/AddUser" type="concreteCommands.addUser">
            <forward name="Success" path="/altaUsuario.jsp"/>
            <forward name="Fail" path="/altaUsuario.jsp"/>
        </command>

        <command path="/SearchUser" type="concreteCommands.searchUser">
            <forward name="SuccessDelete" path="/EliminarUsuario.jsp"/>
            <forward name="SuccessEdit" path="/EditarUsuario.jsp"/>
            <forward name="FailDelete" path="/EliminarUsuario.jsp"/>
            <forward name="FailEdit" path="/EditarUsuario.jsp"/>
        </command>

        <command path="/DeleteUser" type="concreteCommands.deleteUser">
            <forward name="Success" path="/EliminarUsuario.jsp"/>
            <forward name="Fail" path="/EliminarUsuario.jsp"/>
        </command>

    </command-mappings>
</mvc-config>

=== pablodmv/frameworkdc/Libreta/Libreta-war/web/WEB-INF/mvc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mvc-config SYSTEM "mvc.dtd">
<!--
    Document   : mvcTest.xml
    Created on : 23 de octubre de 2010, 04:47 PM
    Author     : Gustavo Leites
    Description:
        Purpose of the document follows.
-->

<mvc-config>
    <command-mappings>
        <command path="/Bienvenido" forwardTo="/Bienvenido.jsp"/>
        <command path="/Login" forwardTo="/Login.jsp"/>

        <!--Comandos simples sobre Usuarios -->
        <command path="/addUser" forwardTo="/altaUsuario.jsp"/>
        <command path="/editUser" forwardTo="/EditarUsuario.jsp"/>
        <command path="/deleteUser" forwardTo="/EliminarUsuario.jsp"/>
        <command path="/queryUser" forwardTo="/QueryUsuario.jsp"/>

        <!--Comandos simples sobre Contactos -->
        <command path="/addContact" forwardTo="/AltaContacto.jsp"/>
        <command path="/deleteContact" forwardTo="/EliminarContacto.jsp"/>
        <command path="/editContact" forwardTo="/EditarContacto.jsp"/>
        <command path="/queryContact" forwardTo="/QueryContacto.jsp"/>

        <command path="/Check" type="concreteCommands.ComandoConcreto">
            <forward name="Success" path="/Bienvenido.jsp"/>
            <forward name="Fail" path="/Error.jsp"/>
        </command>

        <!--Comandos compuestos  sobre Usuarios  -->

        <command path="/AddUser" type="concreteCommands.addUser">
            <forward name="Success" path="/altaUsuario.jsp"/>
            <forward name="Fail" path="/altaUsuario.jsp"/>
        </command>

        <command path="/SearchUser" type="concreteCommands.searchUser">
            <forward name="SuccessDelete" path="/EliminarUsuario.jsp"/>
            <forward name="SuccessEdit" path="/EditarUsuario.jsp"/>
            <forward name="FailDelete" path="/EliminarUsuario.jsp"/>
            <forward name="FailEdit" path="/EditarUsuario.jsp"/>
        </command>

        <command path="/DeleteUser" type="concreteCommands.deleteUser">
            <forward name="Success" path="/EliminarUsuario.jsp"/>
            <forward name="Fail" path="/EliminarUsuario.jsp"/>
        </command>

        <command path="/QueryUser" type="concreteCommands.QueryUser">
            <forward name="Success" path="/QueryUsuario.jsp"/>
            <forward name="Fail" path="/QueryUsuario.jsp"/>
        </command>

        <!--Comandos compuestos  sobre Contactos  -->
        <command path="/AddContact" type="concreteCommands.AddContact">
            <forward name="Success" path="/AltaContacto.jsp"/>
            <forward name="Fail" path="/AltaContacto.jsp"/>
        </command>

        <command path="/SearchContact" type="concreteCommands.SearchContact">
            <forward name="SuccessDelete" path="/EliminarContacto.jsp"/>
            <forward name="SuccessEdit" path="/EditarContacto.jsp"/>
            <forward name="FailDelete" path="/EliminarContacto.jsp"/>
            <forward name="FailEdit" path="/EditarContacto.jsp"/>
        </command>

        <command path="/DeleteContact" type="concreteCommands.DeleteContact">
            <forward name="Success" path="/EliminarContacto.jsp"/>
            <forward name="Fail" path="/EliminarContacto.jsp"/>
        </command>

        <command path="/QueryContact" type="concreteCommands.QueryContacto">
            <forward name="Success" path="/QueryContacto.jsp"/>
            <forward name="Fail" path="/QueryContacto.jsp"/>
        </command>

    </command-mappings>
</mvc-config>

=== pablodmv/frameworkdc/trunk/FrameworkDC/test/jdomTest/mvcTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--DOCTYPE de prueba -->
<!DOCTYPE mvc-config SYSTEM "src/xmlParse/mvc.dtd">
<!--
    Document   : mvcTest.xml
    Created on : 23 de octubre de 2010, 04:47 PM
    Author     : Gustavo Leites
    Description:
        Purpose of the document follows.
-->

<mvc-config>
    <command-mappings>
        <command path="/Bienvenido" forwardTo="/paginas/Bienvenido.jsp"/>
        <command path="/Login" forwardTo="/paginas/Login.jsp"/>

        <command path="/LoginSubmit" type="app.LoginCommand">
            <forward name="entrar" path="/paginas/Principal.jsp"/>
            <forward name="error" path="/paginas/Login.jsp"/>
        </command>

        <command path="/Logout" type="app.LogoutCommand">
            <forward name="ok" path="/paginas/Login.jsp"/>
        </command>

    </command-mappings>
</mvc-config>
